/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteIndexRouteImport } from './routes/website/index'
import { Route as WebsiteReservationsRouteImport } from './routes/website/reservations'
import { Route as WebsiteMenuRouteImport } from './routes/website/menu'
import { Route as WebsiteContactRouteImport } from './routes/website/contact'
import { Route as WebsiteAboutRouteImport } from './routes/website/about'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppProductionRouteImport } from './routes/_app/production'
import { Route as AppPosWaiterRouteImport } from './routes/_app/pos-waiter'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as WebsiteMenuSlugRouteImport } from './routes/website/menu.$slug'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminTablesRouteImport } from './routes/_app/admin.tables'
import { Route as AppStockCountRouteImport } from './routes/_app/stock-count'
import { Route as AppReconciliationRouteImport } from './routes/_app/reconciliation'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteReservationsRoute = WebsiteReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteMenuRoute = WebsiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteAboutRoute = WebsiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WebsiteRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPosWaiterRoute = AppPosWaiterRouteImport.update({
  id: '/pos-waiter',
  path: '/pos-waiter',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const WebsiteMenuSlugRoute = WebsiteMenuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebsiteMenuRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTablesRoute = AppAdminTablesRouteImport.update({
  id: '/admin/tables',
  path: '/admin/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppStockCountRoute = AppStockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationRoute = AppReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waiter': typeof WaiterRoute
  '/website': typeof WebsiteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/menu': typeof AppMenuRoute
  '/pos': typeof AppPosRoute
  '/pos-waiter': typeof AppPosWaiterRoute
  '/production': typeof AppProductionRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/menu': typeof WebsiteMenuRouteWithChildren
  '/website/reservations': typeof WebsiteReservationsRoute
  '/website/': typeof WebsiteIndexRoute
  '/admin/tables': typeof AppAdminTablesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/stock-count': typeof AppStockCountRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/website/menu/$slug': typeof WebsiteMenuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waiter': typeof WaiterRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/menu': typeof AppMenuRoute
  '/pos': typeof AppPosRoute
  '/pos-waiter': typeof AppPosWaiterRoute
  '/production': typeof AppProductionRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/menu': typeof WebsiteMenuRouteWithChildren
  '/website/reservations': typeof WebsiteReservationsRoute
  '/website': typeof WebsiteIndexRoute
  '/admin/tables': typeof AppAdminTablesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/stock-count': typeof AppStockCountRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/website/menu/$slug': typeof WebsiteMenuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waiter': typeof WaiterRoute
  '/website': typeof WebsiteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/pos-waiter': typeof AppPosWaiterRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/menu': typeof WebsiteMenuRouteWithChildren
  '/website/reservations': typeof WebsiteReservationsRoute
  '/website/': typeof WebsiteIndexRoute
  '/_app/admin/tables': typeof AppAdminTablesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/stock-count': typeof AppStockCountRoute
  '/_app/reconciliation': typeof AppReconciliationRoute
  '/website/menu/$slug': typeof WebsiteMenuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/waiter'
    | '/website'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/menu'
    | '/pos'
    | '/pos-waiter'
    | '/production'
    | '/recipes'
    | '/reports'
    | '/reservations'
    | '/website/about'
    | '/website/contact'
    | '/website/menu'
    | '/website/reservations'
    | '/website/'
    | '/admin/tables'
    | '/admin/users'
    | '/stock-count'
    | '/reconciliation'
    | '/website/menu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/waiter'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/menu'
    | '/pos'
    | '/pos-waiter'
    | '/production'
    | '/recipes'
    | '/reports'
    | '/reservations'
    | '/website/about'
    | '/website/contact'
    | '/website/menu'
    | '/website/reservations'
    | '/website'
    | '/admin/tables'
    | '/admin/users'
    | '/stock-count'
    | '/reconciliation'
    | '/website/menu/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/waiter'
    | '/website'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/menu'
    | '/_app/pos'
    | '/_app/pos-waiter'
    | '/_app/production'
    | '/_app/recipes'
    | '/_app/reports'
    | '/_app/reservations'
    | '/website/about'
    | '/website/contact'
    | '/website/menu'
    | '/website/reservations'
    | '/website/'
    | '/_app/admin/tables'
    | '/_app/admin/users'
    | '/_app/stock-count'
    | '/_app/reconciliation'
    | '/website/menu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  WaiterRoute: typeof WaiterRoute
  WebsiteRoute: typeof WebsiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/reservations': {
      id: '/website/reservations'
      path: '/reservations'
      fullPath: '/website/reservations'
      preLoaderRoute: typeof WebsiteReservationsRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/menu': {
      id: '/website/menu'
      path: '/menu'
      fullPath: '/website/menu'
      preLoaderRoute: typeof WebsiteMenuRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/contact': {
      id: '/website/contact'
      path: '/contact'
      fullPath: '/website/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/about': {
      id: '/website/about'
      path: '/about'
      fullPath: '/website/about'
      preLoaderRoute: typeof WebsiteAboutRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos-waiter': {
      id: '/_app/pos-waiter'
      path: '/pos-waiter'
      fullPath: '/pos-waiter'
      preLoaderRoute: typeof AppPosWaiterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/website/menu/$slug': {
      id: '/website/menu/$slug'
      path: '/$slug'
      fullPath: '/website/menu/$slug'
      preLoaderRoute: typeof WebsiteMenuSlugRouteImport
      parentRoute: typeof WebsiteMenuRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tables': {
      id: '/_app/admin/tables'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AppAdminTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-count': {
      id: '/_app/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof AppStockCountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation': {
      id: '/_app/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AppReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMenuRoute: typeof AppMenuRoute
  AppPosRoute: typeof AppPosRoute
  AppPosWaiterRoute: typeof AppPosWaiterRoute
  AppProductionRoute: typeof AppProductionRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppAdminTablesRoute: typeof AppAdminTablesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppStockCountRoute: typeof AppStockCountRoute
  AppReconciliationRoute: typeof AppReconciliationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMenuRoute: AppMenuRoute,
  AppPosRoute: AppPosRoute,
  AppPosWaiterRoute: AppPosWaiterRoute,
  AppProductionRoute: AppProductionRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppAdminTablesRoute: AppAdminTablesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppStockCountRoute: AppStockCountRoute,
  AppReconciliationRoute: AppReconciliationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WebsiteMenuRouteChildren {
  WebsiteMenuSlugRoute: typeof WebsiteMenuSlugRoute
}

const WebsiteMenuRouteChildren: WebsiteMenuRouteChildren = {
  WebsiteMenuSlugRoute: WebsiteMenuSlugRoute,
}

const WebsiteMenuRouteWithChildren = WebsiteMenuRoute._addFileChildren(
  WebsiteMenuRouteChildren,
)

interface WebsiteRouteChildren {
  WebsiteAboutRoute: typeof WebsiteAboutRoute
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteMenuRoute: typeof WebsiteMenuRouteWithChildren
  WebsiteReservationsRoute: typeof WebsiteReservationsRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteAboutRoute: WebsiteAboutRoute,
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteMenuRoute: WebsiteMenuRouteWithChildren,
  WebsiteReservationsRoute: WebsiteReservationsRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  WaiterRoute: WaiterRoute,
  WebsiteRoute: WebsiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
